### ISSUE TITLE
Do you have this working on ECS?

### ISSUE THREAD

**Issue by joglekara** [avishayil/jupyter-ecs-service#1]
Hi, sorry for raising an issue, because it's not really an issue, I just didn't know how to reach out to you and perhaps others might find it helpful too.

Very nice work. I find that I manage to get jupyterhub running on ECS but I can't seem to spin up a task using the LocalSpawner. I eventually get a timeout. I increased the time to 5 minutes to no avail.

The logs show a 500 error "Unable to start server" within 10 seconds so something is going wrong fairly immediately. I just wanted to see if you ever ran into this problem.

Thanks in advance 🙏🏾

**Comment by avishayil** [comment]
Hello @joglekara , thanks for trying this project.
I haven't completely understood your usecase, but I sent you an email to the address on your public profile, maybe I can help you look on that "issue".
Thanks!
